#include <pgwire/types.hpp>

namespace pgwire {

int16_t get_oid_size(Oid oid) {
    switch (oid) {
    case Oid::Bool:
        return 1;
    case Oid::Bytea:
        return -1;
    case Oid::Char:
        return 1;
    case Oid::Name:
        return 64;
    case Oid::Int8:
        return 8;
    case Oid::Int2:
        return 2;
    case Oid::Int2Vector:
        return -1;
    case Oid::Int4:
        return 4;
    case Oid::Regproc:
        return 4;
    case Oid::Text:
        return -1;
    case Oid::Oid:
        return 4;
    case Oid::Tid:
        return 6;
    case Oid::Xid:
        return 4;
    case Oid::Cid:
        return 4;
    case Oid::OidVector:
        return -1;
    case Oid::PgDdlCommand:
        return 8;
    case Oid::PgType:
        return -1;
    case Oid::PgAttribute:
        return -1;
    case Oid::PgProc:
        return -1;
    case Oid::PgClass:
        return -1;
    case Oid::Json:
        return -1;
    case Oid::Xml:
        return -1;
    case Oid::XmlArray:
        return -1;
    case Oid::PgNodeTree:
        return -1;
    case Oid::JsonArray:
        return -1;
    case Oid::PgTypeArray:
        return -1;
    case Oid::TableAmHandler:
        return 4;
    case Oid::PgAttributeArray:
        return -1;
    case Oid::Xid8Array:
        return -1;
    case Oid::PgProcArray:
        return -1;
    case Oid::PgClassArray:
        return -1;
    case Oid::IndexAmHandler:
        return 4;
    case Oid::Point:
        return 16;
    case Oid::Lseg:
        return 32;
    case Oid::Path:
        return -1;
    case Oid::Box:
        return 32;
    case Oid::Polygon:
        return -1;
    case Oid::Line:
        return 24;
    case Oid::LineArray:
        return -1;
    case Oid::Cidr:
        return -1;
    case Oid::CidrArray:
        return -1;
    case Oid::Float4:
        return 4;
    case Oid::Float8:
        return 8;
    case Oid::Unknown:
        return -2;
    case Oid::Circle:
        return 24;
    case Oid::CircleArray:
        return -1;
    case Oid::MacAddr8:
        return 8;
    case Oid::MacAddr8Array:
        return -1;
    case Oid::Money:
        return 8;
    case Oid::MoneyArray:
        return -1;
    case Oid::MacAddr:
        return 6;
    case Oid::Inet:
        return -1;
    case Oid::BoolArray:
        return -1;
    case Oid::ByteaArray:
        return -1;
    case Oid::CharArray:
        return -1;
    case Oid::NameArray:
        return -1;
    case Oid::Int2Array:
        return -1;
    case Oid::Int2VectorArray:
        return -1;
    case Oid::Int4Array:
        return -1;
    case Oid::RegprocArray:
        return -1;
    case Oid::TextArray:
        return -1;
    case Oid::TidArray:
        return -1;
    case Oid::XidArray:
        return -1;
    case Oid::CidArray:
        return -1;
    case Oid::OidVectorArray:
        return -1;
    case Oid::BpcharArray:
        return -1;
    case Oid::VarcharArray:
        return -1;
    case Oid::Int8Array:
        return -1;
    case Oid::PointArray:
        return -1;
    case Oid::LsegArray:
        return -1;
    case Oid::PathArray:
        return -1;
    case Oid::BoxArray:
        return -1;
    case Oid::Float4Array:
        return -1;
    case Oid::Float8Array:
        return -1;
    case Oid::PolygonArray:
        return -1;
    case Oid::OidArray:
        return -1;
    case Oid::Aclitem:
        return 12;
    case Oid::AclitemArray:
        return -1;
    case Oid::MacAddrArray:
        return -1;
    case Oid::InetArray:
        return -1;
    case Oid::Bpchar:
        return -1;
    case Oid::Varchar:
        return -1;
    case Oid::Date:
        return 4;
    case Oid::Time:
        return 8;
    case Oid::Timestamp:
        return 8;
    case Oid::TimestampArray:
        return -1;
    case Oid::DateArray:
        return -1;
    case Oid::TimeArray:
        return -1;
    case Oid::TimestampTz:
        return 8;
    case Oid::TimestampTzArray:
        return -1;
    case Oid::Interval:
        return 16;
    case Oid::IntervalArray:
        return -1;
    case Oid::NumericArray:
        return -1;
    case Oid::PgDatabase:
        return -1;
    case Oid::CstringArray:
        return -1;
    case Oid::TimeTz:
        return 12;
    case Oid::TimeTzArray:
        return -1;
    case Oid::Bit:
        return -1;
    case Oid::BitArray:
        return -1;
    case Oid::Varbit:
        return -1;
    case Oid::VarbitArray:
        return -1;
    case Oid::Numeric:
        return -1;
    case Oid::RefCursor:
        return -1;
    case Oid::RefCursorArray:
        return -1;
    case Oid::RegProcedure:
        return 4;
    case Oid::RegOper:
        return 4;
    case Oid::RegOperator:
        return 4;
    case Oid::Regclass:
        return 4;
    case Oid::Regtype:
        return 4;
    case Oid::RegProcedureArray:
        return -1;
    case Oid::RegOperArray:
        return -1;
    case Oid::RegOperatorArray:
        return -1;
    case Oid::RegclassArray:
        return -1;
    case Oid::RegtypeArray:
        return -1;
    case Oid::Record:
        return -1;
    case Oid::Cstring:
        return -2;
    case Oid::Any:
        return 4;
    case Oid::AnyArray:
        return -1;
    case Oid::Void:
        return 4;
    case Oid::Trigger:
        return 4;
    case Oid::LanguageHandler:
        return 4;
    case Oid::Internal:
        return 8;
    case Oid::Anyelement:
        return 4;
    case Oid::RecordArray:
        return -1;
    case Oid::AnynonArray:
        return 4;
    case Oid::PgAuthid:
        return -1;
    case Oid::PgAuthMembers:
        return -1;
    case Oid::TxidSnapshotArray:
        return -1;
    case Oid::Uuid:
        return 16;
    case Oid::UuidArray:
        return -1;
    case Oid::TxidSnapshot:
        return -1;
    case Oid::FdwHandler:
        return 4;
    case Oid::PgLsn:
        return 8;
    case Oid::PgLsnArray:
        return -1;
    case Oid::TsmHandler:
        return 4;
    case Oid::PgNdistinct:
        return -1;
    case Oid::PgDependencies:
        return -1;
    case Oid::Anyenum:
        return 4;
    case Oid::TsVector:
        return -1;
    case Oid::Tsquery:
        return -1;
    case Oid::GtsVector:
        return -1;
    case Oid::TsVectorArray:
        return -1;
    case Oid::GtsVectorArray:
        return -1;
    case Oid::TsqueryArray:
        return -1;
    case Oid::Regconfig:
        return 4;
    case Oid::RegconfigArray:
        return -1;
    case Oid::Regdictionary:
        return 4;
    case Oid::RegdictionaryArray:
        return -1;
    case Oid::Jsonb:
        return -1;
    case Oid::JsonbArray:
        return -1;
    }

    return -1;
}

} // namespace pgwire